version: '3.8'

services:
  frontend:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./web/index.html:/usr/share/nginx/html/index.html:ro

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
